### ISSUE TITLE
Incompatability with betteranimalsplus Mod:  Server-Crash

### ISSUE THREAD

**Issue by PanHandle** [Budschie/BudschieMorphMod#28]
When killing coyote, player caused a crash that shut down the server. (attached log)

Could souls skip the "pickup" step in config? 
```
16:27.590] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
	at de.budschie.bmorph.json_integration.NBTPath.copyTo(NBTPath.java:48) ~[bmorph:1.16.5-2.0.1]
	at de.budschie.bmorph.json_integration.JsonMorphNBTHandler.applyDefaultNBTData(JsonMorphNBTHandler.java:68) ~[bmorph:1.16.5-2.0.1]
	at de.budschie.bmorph.morph.fallback.FallbackMorphManager.createMorph(FallbackMorphManager.java:37) ~[bmorph:1.16.5-2.0.1]
	at de.budschie.bmorph.morph.fallback.FallbackMorphManager.createMorph(FallbackMorphManager.java:12) ~[bmorph:1.16.5-2.0.1]
	at de.budschie.bmorph.morph.IMorphManager.createMorph(IMorphManager.java:17) ~[bmorph:1.16.5-2.0.1]
	at de.budschie.bmorph.morph.fallback.FallbackMorphManager.createMorphFromEntity(FallbackMorphManager.java:25) ~[bmorph:1.16.5-2.0.1]
	at de.budschie.bmorph.morph.fallback.FallbackMorphManager.createMorphFromEntity(FallbackMorphManager.java:12) ~[bmorph:1.16.5-2.0.1]
	at de.budschie.bmorph.morph.MorphManagerHandlers.createMorphFromDeadEntity(MorphManagerHandlers.java:39) ~[bmorph:1.16.5-2.0.1]
	at de.budschie.bmorph.events.Events.onPlayerKilledLivingEntity(Events.java:122) ~[bmorph:1.16.5-2.0.1]
	at net.minecraftforge.eventbus.ASMEventHandler_32_Events_onPlayerKilledLivingEntity_LivingDeathEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:374) ~[forge:?]
	at net.minecraft.entity.LivingEntity.func_70645_a(LivingEntity.java:1183) ~[?:?]
	at net.minecraft.entity.passive.TameableEntity.func_70645_a(SourceFile:213) ~[?:?]
	at its_meow.betteranimalsplus.common.entity.EntityFeralWolf.func_70645_a(EntityFeralWolf.java:111) ~[betteranimalsplus:10.2.0]
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1059) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70097_a(AnimalEntity.java:73) ~[?:?]
	at its_meow.betteranimalsplus.common.entity.EntityFeralWolf.func_70097_a(EntityFeralWolf.java:186) ~[betteranimalsplus:10.2.0]
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326) ~[?:?]
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?]
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?]
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more
```

**Comment by Budschie** [comment]
This is a bug that I fixed a few days ago, and the fix will be included in the next release of the mod.
