### ISSUE TITLE
morphing into any mob freezes then crashes minecraft

### ISSUE THREAD

**Issue by KrystalTheFox** [Budschie/BudschieMorphMod#4]
hello. when ever i try to morph into any mob, the game freeze and them crashes about a minute later. please help.

crash report: https://pastebin.pl/view/27768f1c
Steps to reproduce. try morphing as any mob and the game will freeze and eventually crash

**Comment by Budschie** [comment]
So, the issue is that a method is being called that is not present on the server. As this method is Forge Code, my guess would be that you are using an old version of forge. Try updating to the latest 1.16.5 forge version and inform me if that solves the issue.

**Comment by m12lrpv** [comment]
my daughter is getting the same. Fresh install of forge 16.5. Only bmorph mod installed. Try and morph and the game hangs (well java hangs)


[01Oct2021 07:53:49.984] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraftforge.event.entity.EntityEvent$Size.setNewSize(Lnet/minecraft/entity/EntitySize;Z)V
	at de.budschie.bmorph.events.Events.lambda$onCalculatingAABB$7(Events.java:382) ~[?:1.16.5-2.0.1]
	at de.budschie.bmorph.events.Events$$Lambda$5874/85440171.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at de.budschie.bmorph.events.Events.onCalculatingAABB(Events.java:364) ~[?:1.16.5-2.0.1]
	at net.minecraftforge.eventbus.ASMEventHandler_32_Events_onCalculatingAABB_Size.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2567/303402789.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.getEntitySizeForge(ForgeEventFactory.java:751) ~[?:?]
	at net.minecraft.entity.Entity.func_213323_x_(Entity.java:2360) ~[?:?]
	at de.budschie.bmorph.events.Events.onMorphedServer(Events.java:289) ~[?:1.16.5-2.0.1]
	at net.minecraftforge.eventbus.ASMEventHandler_25_Events_onMorphedServer_Post.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2567/303402789.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at de.budschie.bmorph.morph.MorphUtil.morphToServer(MorphUtil.java:76) ~[?:1.16.5-2.0.1]
	at de.budschie.bmorph.morph.MorphUtil.morphToServer(MorphUtil.java:24) ~[?:1.16.5-2.0.1]
	at de.budschie.bmorph.network.MorphRequestMorphIndexChange.lambda$handle$0(MorphRequestMorphIndexChange.java:59) ~[?:1.16.5-2.0.1]
	at de.budschie.bmorph.network.MorphRequestMorphIndexChange$$Lambda$6336/1683890039.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at de.budschie.bmorph.network.MorphRequestMorphIndexChange.handle(MorphRequestMorphIndexChange.java:37) ~[?:1.16.5-2.0.1]
	at de.budschie.bmorph.network.MorphRequestMorphIndexChange.handle(MorphRequestMorphIndexChange.java:20) ~[?:1.16.5-2.0.1]
	at de.budschie.bmorph.network.MainNetworkChannel$$Lambda$3738/2124158520.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$5764/1108804184.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2929/1647303553.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2931/1858583776.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2567/303402789.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$5752/1212472187.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$5849/955828574.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5222/1174724689.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[01Oct2021 07:53:49.998] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 9d19d49c-675f-43c3-b0ad-fac46fb02ad6
[01Oct2021 07:53:49.998] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 0a59d658-8d27-4fb0-85dd-63381a663c0a

And i get this error trying to upload the "LOG" file.

![image](https://user-images.githubusercontent.com/23512528/135538430-d3ff2674-4a14-4a64-84b9-c6d7a157251a.png)

**Comment by m12lrpv** [comment]
Actually I realised it's an issue with the default launcher and how it handles Java versions in use with forge. With a different launcher it works fine.
