### ISSUE TITLE
OnDatapackSyncEvent NoClassDefFoundError

### ISSUE THREAD

**Issue by nivthefox** [Budschie/BudschieMorphMod#40]
This seems unfortunate.  Using 3.0.0.

```[08Nov2021 13:01:50.510] [modloading-worker-9/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: bmorph, class de.budschie.bmorph.main.BMorphMod
java.lang.NoClassDefFoundError: net/minecraftforge/event/OnDatapackSyncEvent
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_301]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_301]
	at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.8.0_301]
	at java.lang.Class.getMethods(Unknown Source) ~[?:1.8.0_301]
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_301]
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.2]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_301]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_301]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_301]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_301]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_301]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.OnDatapackSyncEvent
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_301]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
	... 17 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_301]
		at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_301]
		at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.8.0_301]
		at java.lang.Class.getMethods(Unknown Source) ~[?:1.8.0_301]
		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-4.0.0.jar:?]
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-4.0.0.jar:?]
		at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?]
		at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_301]
		at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.2]
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_301]
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_301]
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_301]
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_301]
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_301]
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_301]
[08Nov2021 13:01:50.531] [modloading-worker-9/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 36.2.0, for MC 1.16.5 with MCP 20210115.111550```

**Comment by nivthefox** [comment]
Update: This occurs in 36.2.0 (the current "recommended" forge version), but seems to not occur from 36.2.4 onwards.  I think you just need to make sure you list that version as the minimum required somewhere and you're golden.  Technically you should do that in the Meta-Inf thing, but you can just do that next release.

**Comment by Budschie** [comment]
Alright, fixed :+1:
