### ISSUE TITLE
Server crash when Player leaves while morphed

### ISSUE THREAD

**Issue by Krippi** [Budschie/BudschieMorphMod#74]
When a player leaves the server while he is morphed. 
All player get kicked and you cant join anymore.

`[16:07:36] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_21051_(net.minecraft.world.entity.ai.attributes.Attribute)" because "player" is null
	at de.budschie.bmorph.morph.functionality.configurable.BlockPassthroughAbility.lambda$onPlayerTick$1(BlockPassthroughAbility.java:74) ~[bmorph-1.18.1-2.0.1.jar%2369!/:1.18.1-2.0.1]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at de.budschie.bmorph.morph.functionality.configurable.BlockPassthroughAbility.onPlayerTick(BlockPassthroughAbility.java:68) ~[bmorph-1.18.1-2.0.1.jar%2369!/:1.18.1-2.0.1]
	at net.minecraftforge.eventbus.ASMEventHandler_848_BlockPassthroughAbility_onPlayerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:873) ~[forge-1.18.1-39.1.2-universal.jar%23210!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.18.1-20211210.034407-srg.jar%23206!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23206!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23206!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by CKylinMC** [comment]
arlight 1.16.5 got this problem too :(
