### ISSUE TITLE
Crash on multiplayer screen

### ISSUE THREAD

**Issue by jelebruh** [Budschie/BudschieMorphMod#90]
Some players report bug when enter in multiplayer they minecraft crash with render error

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}

[Log 1](https://jelebruh.xyz/files/mp1.txt) 
[Log 2](https://jelebruh.xyz/files/mp2.txt)

**Comment by Budschie** [comment]
Based on when I last saw the error message, I *think* it has something to do with using an older morph mod version but a new version of Forge. It would be really helpful if you were to tell me both your forge version and the version of this mod so that I can evaluate whether these versions are compatible or not.
